export const BOLIVIA_MUNICIPALITIES_BY_DEPARTMENT: Record<string, readonly string[]> = {
  Beni: [
    'Baures',
    'Exaltación',
    'Guayaramerín',
    'Huacaraje',
    'Loreto',
    'Magdalena',
    'Puerto Siles',
    'Reyes',
    'Riberalta',
    'Rurrenabaque',
    'San Andrés',
    'San Borja',
    'San Ignacio',
    'San Javier',
    'San Joaquín',
    'San Ramón',
    'Santa Ana',
    'Santa Rosa',
    'Trinidad',
  ],
  Chuquisaca: [
    'Azurduy',
    'Camargo',
    'Culpina',
    'El Villar',
    'Huacareta',
    'Huacaya',
    'Icla',
    'Incahuasi',
    'Mojocoya',
    'Camataqui',
    'Las Carreras',
    'Macharetí',
    'Monteagudo',
    'Padilla',
    'Poroma',
    'Presto',
    'San Lucas',
    'Sopachuy',
    'Sucre',
    'Tarabuco',
    'Tomina',
    'Villa Alcalá',
    'Villa Abecia',
    'Villa Charcas',
    'Villa Serrano',
    'Villa Vaca Guzmán',
    'Villa Zudáñez',
    'Tarvita',
    'Yotala',
    'Yamparáez',
  ],
  Cochabamba: [
    'Aiquile',
    'Alalay',
    'Anzaldo',
    'Arani',
    'Arbieto',
    'Arque',
    'Ayopaya',
    'Bolívar',
    'Capinota',
    'Chimoré',
    'Cliza',
    'Cocapata',
    'Cochabamba',
    'Colcapirhua',
    'Colomi',
    'Cuchumuela',
    'Entre Ríos',
    'Mizque',
    'Morochata',
    'Villa Rivero',
    'Omereque',
    'Pasorapa',
    'Pocona',
    'Pojo',
    'Puerto Villarroel',
    'Punata',
    'Quillacollo',
    'Sacaba',
    'Sacabamba',
    'San Benito',
    'Santiváñez',
    'Shinahota',
    'Sicaya',
    'Sipe Sipe',
    'Tacachi',
    'Tacopaya',
    'Tapacarí',
    'Tarata',
    'Tiquipaya',
    'Tiraque',
    'Toco',
    'Tolata',
    'Totora',
    'Vacas',
    'Vila Vila',
    'Villa Tunari',
    'Vinto',
  ],
  'La Paz': [
    'Achacachi',
    'Achocalla',
    'Alto Beni',
    'Ancoraimes',
    'Apolo',
    'Aucapata',
    'Ayata',
    'Ayo Ayo',
    'Batallas',
    'Cairoma',
    'Cajuata',
    'Calacoto',
    'Calamarca',
    'Caquiaviri',
    'Caranavi',
    'Catacora',
    'Chacarilla',
    'Charaña',
    'Chúa Cocani',
    'Chulumani',
    'Chuma',
    'Collana',
    'Colquencha',
    'Colquiri',
    'Comanche',
    'Combaya',
    'Copacabana',
    'Coripata',
    'Coro Coro',
    'Coroico',
    'Curva',
    'Desaguadero',
    'El Alto',
    'Escoma',
    'General Juan José Pérez',
    'Guanay',
    'Guaqui',
    'Huatajata',
    'Huarina',
    'Humanata',
    'Ichoca',
    'Inquisivi',
    'Irupana',
    'Ixiamas',
    'Jesús de Machaca',
    'La Asunta',
    'La Paz',
    'Laja',
    'Licoma Pampa',
    'Luribay',
    'Malla',
    'Mecapaca',
    'Mocomoco',
    'Nazacara de Pacajes',
    'Palca',
    'Palos Blancos',
    'Papel Pampa',
    'Patacamaya',
    'Pelechuco',
    'Pucarani',
    'Puerto Acosta',
    'Puerto Carabuco',
    'Puerto Pérez',
    'Quiabaya',
    'Quime',
    'San Andrés de Machaca',
    'San Buenaventura',
    'San Pedro de Curahuara',
    'San Pedro de Tiquina',
    'Santiago de Callapa',
    'Santiago de Huata',
    'Santiago de Machaca',
    'Sapahaqui',
    'Sica Sica',
    'Sorata',
    'Tacacoma',
    'Taraco',
    'Tiwanaku',
    'Tipuani',
    'Tito Yupanqui',
    'Umala',
    'Viacha',
    'Waldo Ballivián',
    'Yaco',
    'Yanacachi',
  ],
  Oruro: [
    'Andamarca',
    'Antequera',
    'Belén de Andamarca',
    'Caracollo',
    'Carangas',
    'Challapata',
    'Chipaya',
    'Choquecota',
    'Coipasa',
    'Corque',
    'Cruz de Machacamarca',
    'Curahuara de Carangas',
    'El Choro',
    'Escara',
    'Esmeralda',
    'Eucaliptus',
    'Huachacalla',
    'Huanuni',
    'Huayllamarca',
    'La Rivera',
    'Machacamarca',
    'Oruro',
    'Pampa Aullagas',
    'Pazña',
    'Sabaya',
    'Salinas de Garci Mendoza',
    'Santiago de Huari',
    'Santuario de Quillacas',
    'Todos Santos',
    'Toledo',
    'Totora',
    'Turco',
    'Poopó',
    'Yunguyo del Litoral',
  ],
  Pando: [
    'Bella Flor',
    'Bolpebra',
    'Cobija',
    'Filadelfia',
    'Ingavi',
    'Nueva Esperanza',
    'Porvenir',
    'Puerto Gonzalo Moreno',
    'Puerto Rico',
    'San Lorenzo',
    'San Pedro',
    'Santa Rosa del Abuná',
    'Santos Mercado',
    'Sena',
    'Villa Nueva',
  ],
  Potosi: [
    'Acasio',
    'Arampampa',
    'Atocha',
    'Betanzos',
    'Caiza D',
    'Cochas',
    'Caripuyo',
    'Chaquí',
    'Chayanta',
    'Chuquihuta',
    'Colcha K',
    'Colquechaca',
    'Cotagaita',
    'Llallagua',
    'Llica',
    'Mojinete',
    'Ocurí',
    'Pocoata',
    'Porco',
    'Potosí',
    'Puna',
    'Ravelo',
    'Sacaca',
    'San Agustín',
    'San Antonio de Esmoruco',
    'San Pablo de Lípez',
    'San Pedro de Buena Vista',
    'San Pedro de Quemes',
    'Tacobamba',
    'Tahua',
    'Tinguipaya',
    'Tomave',
    'Toro Toro',
    'Tupiza',
    'Uncía',
    'Urmiri',
    'Uyuni',
    'Villazón',
    'Vitichi',
    'Yocalla',
  ],
  'Santa Cruz': [
    'Ascensión de Guarayos',
    'Porongo',
    'Boyuibe',
    'Buena Vista',
    'Cabezas',
    'Camiri',
    'Charagua',
    'Colpa Bélgica',
    'Comarapa',
    'Concepción',
    'Cotoca',
    'Cuatro Cañadas',
    'Cuevo',
    'El Carmen Rivero Tórrez',
    'El Puente',
    'El Torno',
    'Fernández Alonso',
    'General Saavedra',
    'Gutiérrez',
    'La Guardia',
    'Lagunillas',
    'Mairana',
    'Mineros',
    'Montero',
    'Moro Moro',
    'Okinawa',
    'Pailón',
    'Pampa Grande',
    'Portachuelo',
    'Postrer Valle',
    'Pucara',
    'Puerto Quijarro',
    'Puerto Suárez',
    'Quirusillas',
    'Roboré',
    'Saipina',
    'Samaipata',
    'San Antonio del Lomerío',
    'San Carlos',
    'San Ignacio',
    'San Javier',
    'San José',
    'San Julián',
    'San Matías',
    'San Miguel',
    'San Pedro',
    'San Rafael',
    'San Ramón',
    'Santa Cruz de la Sierra',
    'Santa Rosa del Sara',
    'Trigal',
    'Urubichá',
    'Vallegrande',
    'Warnes',
    'Yapacaní',
  ],
  Tarija: [
    'Bermejo',
    'Caraparí',
    'El Puente',
    'Entre Ríos',
    'Padcaya',
    'San Lorenzo',
    'Tarija',
    'Uriondo',
    'Villamontes',
    'Yacuiba',
    'Yunchará',
  ],
};
